### ISSUE TITLE
Test 3.4-IP in preparation for release

### ISSUE THREAD

**Issue by rnicholus** [FineUploader/fine-uploader#766]
- [x] re-test extension validation after work in #735 
- [x] test getName API function - #732
- [x] re-test button-related functions after refactoring in #727 
- [x] ensure `onError` callback is passed XHR in File API supported browsers - #718 
- [x] test `itemLimit` validation option - #635 
- [x] test `onSubmitted` callback - #543 
- [x] test upload via paste - #487 
- [x] regression testing in Chrome (latest)
- [x] regression testing in Firefox (latest)
- [x] regression testing in Android 4
- [x] regression testing in IOS6
- [x] regression testing in Safari OS X (latest)
- [x] regression testing in IE10
- [x] regression testing in IE9
- [x] regression testing in IE8
- [x] regression testing in IE7
