### ISSUE TITLE
Test 3.5-IP in preparation for release

### ISSUE THREAD

**Issue by rnicholus** [FineUploader/fine-uploader#802]
- [x] re-testing pasting in Chrome - #777 
- [x] re-test DnD code - #715, #577
- [x] test FU mode in various layouts - #696 
- [x] test feature detection #680 
- [x] test new `getSuccessful` API method #634 
- [x] regression testing in Chrome (latest)
- [x] regression testing in Firefox (latest)
- [x] regression testing in Android 4
- [x] regression testing in IOS6
- [x] regression testing in Safari OS X (latest)
- [x] regression testing in IE10
- [x] regression testing in IE9
- [x] regression testing in IE8
- [x] regression testing in IE7
- [x] testing in SI
- [x] testing in WMC
