### ISSUE TITLE
Automated Build Scripts

### ISSUE THREAD

**Issue by feltnerm** [FineUploader/fine-uploader#855]
I'm working on a collection of scripts that will help automate the Fine Uploader release process. The priorities are to implement a flexible, cross-browser test strategy and to standardize a build process.
## Tier 1
- [x] #811 **Automated Releases** - This is a priority for this issue. @rnicholus, can we discuss the goals of a "proper" release?
- [x] #810 **Automated Tests**  - [Test stories/scenarios](https://github.com/Widen/fine-uploader/issues/852) must be determined. Methods for cross-browser testing need to be discussed as well. 
- [ ] #835 **Development/Sandbox Server** - If we _really_ want to do some heavy testing, then we are going to have to eventually have some kind of server (for testing chunking, pause/resume, etc.).
## Tier 2
- [ ] #812 **Nightly builds** - I think this is a good idea. How do we want to think about automating this? Would there be a server running a cron job or something? 
- [x] #722 **Automated Documentation Builds**
- [ ] #698 **Bootstrapped Packages** - A Bootstrap/Fine Uploader hybrid could be packaged as part of the build process and hosted/linked to from the main website. There could also be other supported packages (such as the jQuery plugin, #531 Angular.JS  has been mentioned, ...). Or at least just a generic packager that could be extended. This would allow a user to quickly and easily get started with Fine Uploader. Very related to #846. 
- [ ] #789 **AMD/CommonJS Support** - Questionable, but adding AMD/CommonJS could affect the build. Put here just in case.
