### ISSUE TITLE
21 - Update and document all server-side examples

### ISSUE THREAD

**Issue by rnicholus** [FineUploader/fine-uploader#861]
- [x] Java - widen/fine-uploader-server#7
- [ ] ASP.NET C# - widen/fine-uploader-server#8
- [ ] ASP.NET VB - widen/fine-uploader-server#9
- [ ] Coldfusion - widen/fine-uploader-server#10
- [x] Nodejs - widen/fine-uploader-server#11
- [ ] PHP - widen/fine-uploader-server#12
- [x] Python - widen/fine-uploader-server#13
- [ ] Perl - widen/fine-uploader-server#14
- [ ] Rails - widen/fine-uploader-server#15
